### ISSUE TITLE
Cornelis not loading properly for .lagda.md files

### ISSUE THREAD

**Issue by zaxioms** [isovector/cornelis#61] opened 2022-07-06 19:04 UTC
Hi! I"m having an issue specifically with `.lagda.md` files. Whenever I try to load them, my neovim just recognizes them as regular markdown files. Because of this, I can't seem to call `CornelisLoad` or any other related functions. Does anyone know how I can make this work?

My Agda version is 2.6.2.2 (the default when installed with `stack`) and my `stack` install is managed with `ghcup`

Thanks so much!!

~~unrelated, I'm having a minor issue that whenever I open a regular `.agda` file it prompts me with all possible keybinds before letting me edit the file. Is this intended?~~

**Comment by isovector** [comment] 2022-07-06 20:56
I ran into this too. The issue is that neovim's default file type detection
also recognizes markdown files, and wins the conflict.

You can work around it by explicitly setting your file type via `:setf agda`

**Comment by chezbgone** [comment] 2022-07-10 22:56
I automated this with
```vim
autocmd BufNewFile,BufRead *.lagda.md set filetype=agda
```

**Comment by Eloitor** [comment] 2022-07-16 09:14
My configuration is written in lua and I didn't know where to place this. After reading https://neovim.io/doc/user/filetype.html I placed this in ~/.config/nvim/ftdetect/

It works well, but I wonder why "agda" does not appear in the status line...

By the way, 
``` vim
autocmd BufNewFile,BufRead *.lagda.md set filetype=agda.markdown
```
 works better for me, it enable markdown's syntax highlighting,

**Comment by isovector** [comment] 2023-01-26 17:39
Should be fixed in the latest commit; I was using `setf` instead of `setlocal filetype`, which I thought were the same but are not in fact.

**Closed by isovector** 2023-01-26 17:39 UTC
